name: Healthcare CICD workflow

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build tool setup Stage
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Application build Stage
      run: |
           mvn clean install
    - name: Upload to S3
      run: |
          aws s3 ls
      env:
         AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}
         AWS_DEFAULT_REGION: 'us-east-1'

    - name: Docker Build & Push to ECR 
      run: | 
           docker build -t cicd/healthcare . 
           docker tag cicd/healthcare:latest 891376975876.dkr.ecr.us-east-1.amazonaws.com/cicd/healthcare:latest 
           
