name: Healthcare CICD workflow

on:
  workflow_dispatch

jobs:
  build:
    runs-on: mahesh
    steps:
    - uses: actions/checkout@v4      
    - name: Application build Stage
      run: mvn clean install
    - name: Check connectivity with AWS
      run: aws s3 ls

    - name: Docker Build & Push to ECR 
      run: | 
           aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 891376975876.dkr.ecr.us-east-1.amazonaws.com
           docker build -t cicd/healthcare . 
           docker tag cicd/healthcare:latest 891376975876.dkr.ecr.us-east-1.amazonaws.com/cicd/healthcare:latest 
           docker push 891376975876.dkr.ecr.us-east-1.amazonaws.com/cicd/healthcare:latest
           
